### ISSUE TITLE
Other protocols are not included 

### ISSUE THREAD

**Issue by KINGSABRI** [rapid7/rex#11]
Hi 
I'm trying to run a TFTP client and I'm getting `Rex::Proto::TFTP` error. Looking up to the [code](https://github.com/rapid7/rex/blob/91918c46b126717311b848b46a2bacf4914022a9/lib/rex/proto.rb) and I found the TFTP along with other protocols are not included 

The only included protocols are:
- http
- smb
- ntlm
- dcerpc
- drda
- iax2
- kerberos
- rmi

Is there another way to include that is not obvious to me?

**Comment by KINGSABRI** [comment]
Okay, it seems that you have left the other protocol intentionally unloaded to be explicitly required 
```
require 'rex/proto/tftp/client'
```

**Comment by mynameiswillporter** [comment]
Why would this be intentionally left out? I feel like its strange to require users to either edit their modules, or do something like drop into `irb` and run `require 'rex/proto/tftp/client'`. What am I missing here?
