### ISSUE TITLE
2.0.8 breaks backwards compatibility

### ISSUE THREAD

**Issue by gschneider-r7** [rapid7/rex#4]
If looks like the merge from upstream brought in the 2.1.5 min version for Ruby. This should have been part of a higher version bump. As-is, this will break nexpose-client on Ruby 1.9.3 and 2.0.0. We have not yet abandoned support for those versions of Ruby, but it's coming.

For now we will pin to version 2.0.7 to get around this.

**Comment by bliaxiong** [comment]
Changing to Ruby 2.1.5 also breaks support for JRuby as well.

**Comment by hdm** [comment]
JRuby isn't well supported at the moment, due to issues like: https://github.com/jruby/jruby/issues?q=is%3Aopen+is%3Aissue+openssl

**Comment by jmartin-tech** [comment]
Closing stale issue.
