### ISSUE TITLE
warning: constant OpenSSL::SSL::SSLContext::METHODS is deprecated

### ISSUE THREAD

**Issue by KINGSABRI** [rapid7/rex#7]
Hello guys,
I'm getting the following while using `rpc.call` 

```ruby
/var/lib/gems/2.5.0/gems/rex-2.0.12/lib/rex/socket/ssl_tcp.rb:82: warning: constant OpenSSL::SSL::SSLContext::METHODS is deprecated
```
- Ruby version: 2.5.1

I think it should be replaced with 
```ruby
OpenSSL::SSL::SSLContext.methods.include? version
```

If it's too trivial, for a PR, plz reject my PR

**Comment by bcoles** [comment]
No PR is too trivial if it fixes something.

Looking at the [documentation](https://ruby-doc.org/stdlib-2.5.1/libdoc/openssl/rdoc/OpenSSL/SSL/SSLContext.html), it appears that the `METHODS` constant is still supported, so the warning can be safely ignored - at least for now.

I had a quick look at how others are resolving this issue. It seems that hardcoding the `METHODS` array is a common approach:

```
2.3.0 :002 > OpenSSL::SSL::SSLContext::METHODS
 => [:TLSv1, :TLSv1_server, :TLSv1_client, :TLSv1_2, :TLSv1_2_server, :TLSv1_2_client, :TLSv1_1, :TLSv1_1_server, :TLSv1_1_client, :SSLv3, :SSLv3_server, :SSLv3_client, :SSLv23, :SSLv23_server, :SSLv23_client] 
```

This is objectively terrible.

[Another approach](https://github.com/savonrb/httpi/blob/master/lib/httpi/auth/ssl.rb) is something like this:

```ruby
      # Fix for
      # httpi/auth/ssl.rb:13: warning: constant OpenSSL::SSL::SSLContext::METHODS is deprecated
      ssl_context = OpenSSL::SSL::SSLContext
      SSL_VERSIONS = if ssl_context.const_defined? :METHODS_MAP
        ssl_context.const_get(:METHODS_MAP).keys
      else
        ssl_context::METHODS.reject { |method| method.match(/server|client/) }
      end.sort.reverse
```

**Comment by KINGSABRI** [comment]
> I had a quick look at how others are resolving this issue. It seems that hardcoding the METHODS array is a common approach

That's true, and this is what I've done as a fix for my previous stupid mistake

**Comment by semaperepelitsa** [comment]
FYI, you are supposed to use new min_version/max_version attributes instead of constants.

https://github.com/ruby/openssl/pull/142
